### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by quertenmont** [noripyt/django-cachalot#111] opened 2018-07-19 07:33 UTC
Hello,

I am regularly getting the following error with django-cachalot version 2.0.1

`

Request Method: | POST
-- | --
2.0.7
ValueError
max() arg is an empty sequence
/usr/local/lib/python3.5/dist-packages/cachalot/monkey_patch.py in _get_result_or_execute_query, line 47
/usr/bin/python3
3.5.2
['/home/root/project',  '/usr/local/bin',  '/usr/lib/python35.zip',  '/usr/lib/python3.5',  '/usr/lib/python3.5/plat-x86_64-linux-gnu',  '/usr/lib/python3.5/lib-dynload',  '/usr/local/lib/python3.5/dist-packages',  '/usr/lib/python3/dist-packages',  '/home/root/project']
Thu, 19 Jul 2018 07:19:59 +0000
`

This comes from

`
/usr/local/lib/python3.5/dist-packages/cachalot/monkey_patch.py in _get_result_or_execute_query

    data = cache.get_many(table_cache_keys + [cache_key])
    new_table_cache_keys = set(table_cache_keys)
    new_table_cache_keys.difference_update(data)
    if not new_table_cache_keys and cache_key in data:
        timestamp, result = data.pop(cache_key)
        if timestamp >= max(data.values()): ...
            return result
    result = execute_query_func()
    if result.__class__ not in ITERABLES and isinstance(result, Iterable):
        result = list(result)
`

The local variables are:
`
Variable | Value
-- | --
cache | {}
cache_key | '75b3b54db423f451954a42ef4e9bc85b5271935e'
data | {}
execute_query_func | <function _patch_compiler.<locals>.inner.<locals>.<lambda> at 0x7fbcf30fd158>
new_table_cache_keys | set()
result | (1,)
table_cache_keys | []
timestamp | 1531727788.1209958

`

Is there any quick workaround ?

Thanks,
Loic

**Comment by ironman5366** [comment] 2018-07-22 03:53
@quertenmont  I don't know what caused this error, but I was able to at least work around it by modifying the behavior of the line that triggered it. For me, checking if a model with certain parameters existed was triggering it, so I instead used `.count() >= 1`. Here is the original and what I changed it to.

Original: 
`return self.essay_set.filter(document_type=1, status=5).exists()` 

Changed:
`return self.essay_set.filter(document_type=1, status=5).count() >= 1`

Hope that can be of some help.

**Comment by quertenmont** [comment] 2018-07-24 16:53
in my case it's not quite clear what triggers is, but for sure I am not using exists(),
so I don't quite know what to do here

**Comment by BertrandBordage** [comment] 2018-07-27 11:51
Are you both using a model with `managed = False`?

**Comment by quertenmont** [comment] 2018-07-27 12:21
Nop...
But my models have pretty large many to many relations, I suspect that this is part of the issue...
Another possible hint is that when this error appears, I can't save/update objects anymore... no matter what.  I have to manually restart the server (gunicorn actually) to recover a normal state

Loic,

**Comment by BertrandBordage** [comment] 2018-07-27 12:42
Could you also share the query that triggerred that error? Even if it’s anonymized, that’s interesting, because I don’t know any query generated using the ORM that contains no table (which is the origin of the bug).

**Comment by quertenmont** [comment] 2018-07-27 12:48
My DB is postgres and my cache is redis
CACHES = {
        "default": {
                "BACKEND": "django_redis.cache.RedisCache",
                "LOCATION": "redis://django_redis_1:6379/1",
                "OPTIONS": {
                        "CLIENT_CLASS": "django_redis.client.DefaultClient",
                }
        }
}

unfortunately, I can't share the query easily (it was mostly my end user reporting the error while adding model instances via the django admin)

**Comment by BertrandBordage** [comment] 2018-07-27 12:52
OK, thanks.
I made a fix that’ll be in 2.0.2, but I’d still like to reproduce the error to have it in the tests. Right now it looks like dark magic to me ^^

**Comment by BertrandBordage** [comment] 2018-07-27 14:10
I found one possibility!
Did you use `.union`, `.intersection`, or `.difference`?

**Comment by BertrandBordage** [comment] 2018-07-27 18:32
Fixed by 2.0.2.

**Closed by BertrandBordage** 2018-07-27 18:32 UTC
