### ISSUE TITLE
Cache key collisions?

### ISSUE THREAD

**Issue by Natureshadow** [noripyt/django-cachalot#210] opened 2022-02-08 20:39 UTC
## What happened?

We are seeing frequent, strange errors using cachalot in one system that very much seem like a cache key collision.

It's hard to build a reproducer, but this is basically what happened and how we debugged it:

We saw views throwing strange errors, along the lines of model fields having an unexpected type and failing to deserialize. We then anlyzed the query leading up to the issue, and produced its cache key using `cachalot.utils.get_query_cache_key`. We then queried the cache backend for this key, and found an entirely different database object (even another model) under that SHA1 cache key.

While such a collision can happen, it somehow seems odd, because we see a bunch of such cases, not only one. And sadly, of course we can reproduce which queryit is that requests the invalid data form the cache, but we cannot reproduce which query it was that lead up to the other data being stored...

We are using two Django nodes with one Redis cache backend, with Django 3.2 on Debian 11 and Python 3.9.

**Comment by Andrew-Chen-Wang** [comment] 2022-02-08 21:12
That’s not good… please downgrade and see if the issue persists. Let me know what the current cachalot version is and I suggest a downgrade to the previous cachalot major version. It would also be great to see if there was a specific change that caused this to happen at a specific patch version via several downgrades but I understand that may not be possible.

Thank you so much for the report!
________________________________
From: Dominik George ***@***.***>
Sent: Tuesday, February 8, 2022 3:39:51 PM
To: noripyt/django-cachalot ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [noripyt/django-cachalot] Cache key collisions? (Issue #210)


What happened?

We are seeing frequent, strange errors using cachalot in one system that very much seem like a cache key collision.

It's hard to build a reproducer, but this is basically what happened and how we debugged it:

We saw views throwing strange errors, along the lines of model fields having an unexpected type and failing to deserialize. We then anlyzed the query leading up to the issue, and produced its cache key using cachalot.utils.get_query_cache_key. We then queried the cache backend for this key, and found an entirely different database object (even another model) under that SHA1 cache key.

While such a collision can happen, it somehow seems odd, because we see a bunch of such cases, not only one. And sadly, of course we can reproduce which queryit is that requests the invalid data form the cache, but we cannot reproduce which query it was that lead up to the other data being stored...

We are using two Django nodes with one Redis cache backend, with Django 3.2 on Debian 11 and Python 3.9.

**Comment by Natureshadow** [comment] 2022-02-08 21:25
Trying our best to track this down. However, it is one of these bugs that only happen under production workload where experimenting is hard.

**Comment by Natureshadow** [comment] 2022-02-08 22:58
OK, now things are getting exciting.

Digging deeper, we found that we had intermittent issues with PostgreSQL connections being lost due to a badly behaving firewall. These connections produced invalid results from postgres in Django itself (for some reason I cannot yet grasp), and I cannot rule out that these invalid results have been cached by cachalot.

Whether this is related, or not, or… I cannot yet say.

**Comment by Andrew-Chen-Wang** [comment] 2022-02-09 08:28
I wonder if the migration signal happens and cachalot crashes (which invalidates table results). A lost postgres connection should be encased in a transaction block when it comes to migration, so we can rule that out.

One thing to consider is how you're deploying, specifically the design of your migrations such that old servers that perform ORM queries don't find a missing or extra column (ie explicite py listing columns in all ORM queries).

**Comment by Andrew-Chen-Wang** [comment] 2022-03-09 07:33
For now, I'm closing. Please reopen if the issue persists after your resolution.

**Closed** 2022-03-09 07:33 UTC
Labels: invalid, question
