### ISSUE TITLE
Raw queries may cause unintentional invalidations

### ISSUE THREAD

**Issue by jcass77** [noripyt/django-cachalot#122] opened 2018-11-22 13:09 UTC
I have come across a few instances where tables would be invalidated unexpectedly.

I don't understand the testing framework well enough to simulate the problem unfortunately, but think it is related to model fields that have similar names to SQL keywords.

For example, would this [invalidation logic](https://github.com/noripyt/django-cachalot/blob/f3f8773f853d4814ec801b8b7f8a6470781857c8/cachalot/monkey_patch.py#L131-L133) logic not cause a query that contains a field called `created` to trigger an validation?

i.e. ``SELECT id, created, from table``...

**Comment by BertrandBordage** [comment] 2018-11-22 15:46
The policy of django-cachalot is that it’s better to invalidate more than expected instead of less than expected. That’s a mandatory to avoid returning stale data. So there are some cases where django-cachalot may invalidate more than needed.

But it should never happen when you are using the ORM. The invalidation logic you pointed out is only used when using `Model.objects.raw()` or `cursor.execute`. When you’re using the ORM, this logic is never used.

I guess you were talking only about non-ORM queries, given that you mention “raw” in the issue title.
If you’re talking only about raw queries, then yes, asking for a `created` field will trigger an invalidation.

I know, in theory it could be parsed to find whether we are really using a `CREATE` keywoard or not. But that’s more complex than you might think. The ideal solution is to use a parser like `sqlparse`, which is fine because Django has it as a dependency. I already considered doing that instead:
```python
sqlparse.parse(sql)[0].get_type() in {'INSERT', 'UPDATE', 'DELETE', 'CREATE', 'ALTER', 'DROP'}
```
That’s a perfect way to avoid extra invalidations. The problem is that parsing the query this way takes a lot of time. On a simple query like the following one, it already takes 2.3 ms to do that!
```sql
SELECT
	title,
	string_agg(first_name || ' ' || last_name, ', ') AS authors
FROM books
JOIN books_authors ON books_authors.book_id = books.id
JOIN authors ON authors.id = books_authors.author_id
GROUP BY books.id;
```
2.3 ms can be way more than the time needed to run the query. And you will agree with me that most Django queries have more tokens than that, especially because of the long list of selected columns.
With the technique I currently use, it takes less than a μs to do the same, in a more approximate way. So around 2000× faster…

I had to choose between making all raw queries lag, or make a few ORM queries execute more times than needed. Since we write raw queries when we want the best performance, I chose the latter.

So if my answer correctly covers your question, this is a “won’t fix”.

**Comment by jcass77** [comment] 2018-11-23 04:12
Thank you for the detailed explanation.

Did you perhaps consider a pure string parsing approach when evaluating the performance impact?

So something like the code fragment below (haven’t tested this):
```
sql = sql.split()
keywords = [“create”, “alter”, ...]
if any(keyword in sql for keyword in keywords)
   # Invalidate!
```

I don’t use raw queries myself but one the Django packages I am using seems to do so in a way that triggers an invalidation on every request. Not sure what the performance impact of caching and invalidation the affected table is and how it compares with the above.

Agree that a “wont’t fix” is probably fine - thanks!

**Comment by BertrandBordage** [comment] 2018-11-23 14:48
Using a simple split on whitespaces will not cover all cases. This query is perfectly valid SQL:
```sql
(SELECT'1')UNION(SELECT(2));
```
We could use regular expressions to have a better split, but we would have to be perfectly sure that this split supports all the SQL syntaxes from all the supported databases. I honestly think that it’s possible using a rather simple regex such as `[\A\s\(\)'"](?:INSERT|UPDATE|DELETE|CREATE|ALTER|DROP)[\Z\s\(\)'"]`. But that means we have to add a lot of regression tests and monitor syntax changes in PostgreSQL, MySQL & SQLite to update the regex whenever needed.

So I think it’s too risky and requires too much effort for a minor issue. That being said, if three experts of PostgreSQL, MySQL & SQLite want to do the work of monitoring syntax changes, we can add this feature.

Closing for now unless someone has a clever and very fast solution.

**Closed by BertrandBordage** 2018-11-23 14:48 UTC
Labels: needs info
